### ISSUE TITLE
Suggested addition Tours

### ISSUE THREAD

**Issue by andelar** [Vytek/VR-Awesome#7]
Thanks for a fantastic list of resources!

I just released an ambitious project LiveTourLab, built on React VR. It makes VR tours easy to create, and there is nothing quite like it today.

I think Tours will grow to a fairly big category, given the initial popularity of proprietary systems like Matterport even though they are both proprietary and lack most of the functionality we just launched.

With that in mind, I suppose a fitting place would be a subcategory Tours under Software, like the below. Also I will be adding a more diverse set of contributors to the project, let me know if any of you are interested.

## Software
...

### Tours
* [LiveTourLab](https://github.com/livetourlab/live-tour-lab) - Framework for creating VR Tours.

**Comment by Vytek** [comment]
Thank you!
Please, make a pull request ;-)

**Comment by andelar** [comment]
Thank you! Done the PR.
And congrats again for a great repo. I have come back to it many times and found it very useful! Cheers
